systers/powerup-android

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/MainActivity.java, PowerUp/app/src/main/res/values/strings.xml
fixed issue #15 using boolean and shared preferences.
=> changing room opens automatically the first time

PowerUp/app/src/main/java/powerup/systers/com/Game.java, PowerUp/app/src/main/res/layout/pgame.xml, PowerUp/app/src/main/res/values/dimens.xml
Earlier the avatar was being just chosen but a generic image was displayed. Now the chosen avatar is displayed and displayed. Fixed #36 .
=> Chosen avatar is displayed

README.md
Added guideline to create upstream with original repo and be able to sync with the same
=> Added Configure Remote guidelines

PowerUp/app/src/main/res/layout/gamemap.xml, PowerUp/app/src/main/res/values-land/dimens.xml, PowerUp/app/src/main/res/values-sw600dp-port/dimens.xml, PowerUp/app/src/main/res/values-sw600dp/dimens.xml, PowerUp/app/src/main/res/values-sw720dp-port/dimens.xml, PowerUp/app/src/main/res/values-sw720dp/dimens.xml, PowerUp/app/src/main/res/values/dimens.xml
I made changes to gamemap.xml to display buttons in appropriate sizes in both landscape and portrait mode. The dimens.xml is added for following.
For normal phones-
values/dimens.xml
values-land/dimens.xml
For 7" Tablets -
values-sw600dp/dimens.xml
values-sw600dp-port/dimens.xml
For 10" Tablets-
values-sw720dp/dimens.xml
values-sw720dp-port/dimens.xml
=> Adapt gamemap.xml for landscape mode in phones and tablets

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/CompletedSceneActivity.java, PowerUp/app/src/main/java/powerup/systers/com/CreatorRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameOverActivity.java, PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java
Refactoring of the names and solution of some warnings
=> Name refactoring

PowerUp/app/src/main/res/values/strings.xml
=> Fixed small typing error

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java, PowerUp/app/src/main/res/values/strings.xml
All the required changes have been made, I apologize for the inconvenience caused. Will look into how to manage commits better from next time. Fixed #42
=> Start Room opens on pressing Start

PowerUp/app/src/main/res/layout/pgame.xml
1)Added + before newly defined ids in pgame.
2)Removed backgroundTint.
=> Added + before newly defined ids

PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/java/powerup/systers/com/db/PowerUpContract.java
I have separated out DB contracts in a separate file `PowerUpContract.java` as we discussed in Issue #74 . Please check it out and let me know. 
Thanks a lot,
Harshita
=> Separated out DB contracts

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/DressingRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java, PowerUp/app/src/main/res/layout-land/avatar.xml, PowerUp/app/src/main/res/layout-land/dressing_room.xml, PowerUp/app/src/main/res/layout-land/game_activity.xml, PowerUp/app/src/main/res/layout/avatar.xml, PowerUp/app/src/main/res/layout/game_activity.xml, PowerUp/app/src/main/res/layout/gamemap.xml
In this PR following work has been done:
- Landscape layout for game activity developed.
- Avatar's position in landscape mode fixed.
- Added home button in map activity.
- Minor code fixing (including dynamic intent creation and removing hard coded strings).
=> Landscape layouts and avatar fixed

PowerUp/app/src/main/assets/Accessories.csv, PowerUp/app/src/main/assets/Clothes.csv, PowerUp/app/src/main/assets/Hair.csv, PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/java/powerup/systers/com/db/PowerUpContract.java, PowerUp/app/src/main/res/layout-land/activity_select_features.xml, PowerUp/app/src/main/res/layout/activity_select_features.xml, PowerUp/app/src/main/res/values/dimens.xml
The following **tables have been added** to database for Dressing Room 2 implementations:
1. Clothes
2. Hair
3. Accessories
These tables have the following **attributes** : ID, Name, Points, Purchased.
These files have been imported from the **csv files in the asset folder**.
Currently the points required to purchase a feature is **displayed below the image** of feature in the Dressing Room 2. 
**Portrait:**
**Landscape:**
=> Database changes for Dressing Room 2

PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/res/layout-land/activity_select_features.xml, PowerUp/app/src/main/res/layout/activity_select_features.xml, PowerUp/app/src/main/res/values/dimens.xml, PowerUp/app/src/main/res/values/integers.xml, PowerUp/app/src/main/res/values/strings.xml
This pull request contains:
- **Database functions** to set and get purchased items
- **UI changes** to label item as purchased
- **Implementation** of labeling item as purchased
**Portrait:**
**Landscape:**
=> Labeling purchased items in Dressing Room 2

PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/java/powerup/systers/com/db/PowerUpContract.java, PowerUp/app/src/main/res/values/strings.xml
Check points before purchasing an item. If points required to buy an item is more than current points of user, a toast is shown.
=> Check points before purchasing item

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/res/layout-land/avatar.xml, PowerUp/app/src/main/res/layout/avatar.xml
Avatar modified to show accessories purchased on it in final avatar scene.
=> Avatar Modified

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/res/layout-land/avatar.xml, PowerUp/app/src/main/res/layout/avatar.xml
Reverts systers/powerup-android#151 as the changes are not creating the desired effect. Will need some bug fixing before merge.
=> Revert "Avatar Modified"

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/res/layout-land/avatar.xml, PowerUp/app/src/main/res/layout/avatar.xml
1. Avatar modified to show accessories purchased on it in final avatar scene.
2. Database changes to show accessories and save accessories in db.
=> Avatar Modified to display accessories

README.md
There was a couple of file name changes to make it clearer to the user who is setting up their environment.
=> Updating ReadMe document.

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java
The attribute replayed also needed to be reset which was missed in the last PR.Updated it.
=> Added new user functionality

PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java
#176 
@chhavip 
I have tested by removing intent line and it won't mess with user data. Thanks.
=> #176 problem solved

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/CompletedSceneActivity.java, PowerUp/app/src/main/java/powerup/systers/com/DressingRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameOverActivity.java, PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java, PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/Answer.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/Avatar.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/Question.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/Scenario.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/Score.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java, PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java, PowerUp/app/src/main/java/powerup/systers/com/db/PowerUpContract.java
I added headers in all of the files in the datamodel folder, db folder, and activities. Any auto-generated comments have been deleted. I also added descriptions (parameter, purpose, etc.) for newly created functions.
=> Add comments for better understanding

README.md
Added the contributing guidelines.
=> Linked wiki with README

PowerUp/app/src/main/assets/Question.csv
=> fixed errors in questions

PowerUp/app/src/main/AndroidManifest.xml
The title bar in all activities of the app have been removed and now the app has a uniform layout all throughout. Addresses #220 .Please review and merge. Thanks :smile:
=> implemented app uniformity in title bars and layout 

PowerUp/app/src/main/res/layout/completed_game.xml, PowerUp/app/src/main/res/values/dimens.xml
The text view looks like this now. Fixes issue #227 
@chhavip This is updated now. Please review. Thanks. :smile:
=> alignment problem in complete activity addressed

PowerUp/app/src/main/res/layout-land/completed_scene.xml, PowerUp/app/src/main/res/layout/completed_scene.xml, PowerUp/app/src/main/res/values-land/dimens.xml, PowerUp/app/src/main/res/values/dimens.xml
Fixes #299 
**ScreenShots of change**
**In Portrait**
**In Landscape**
@yatna @anubhakushwaha @chhavip @aanchal07 please review this PR. Thanks :)
=> Fixes #299:UI Enhancement in completed_scene.xml

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java, PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java
=> implemented replay button in ScenarioOverActivity

PowerUp/app/src/main/res/layout-land/activity_scenario_over.xml, PowerUp/app/src/main/res/values/dimens.xml
Fixes #291 
@yatna @anubhakushwaha @chhavip @aanchal07 Please review this PR. Thanks :)
=> Fixes #291:Replay and Continue button disappears on orientation change

PowerUp/app/src/main/res/layout-land/game_activity.xml, PowerUp/app/src/main/res/values-land/dimens.xml, PowerUp/app/src/main/res/values-sw360dp/dimens.xml, PowerUp/app/src/main/res/values-sw600dp/dimens.xml, PowerUp/app/src/main/res/values-sw720dp/dimens.xml, PowerUp/app/src/main/res/values/dimens.xml
**Following are the screenshots of the changes I have made**
@anubhakushwaha @chhavip @aanchal07  Please review this PR. Thanks :)
=> Fixes #296:ScenarioNames issue in GameActivity in landscape mode

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/DressingRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java, PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java
Fixes #321 
Fixed:
Removed all the context classes in **static** fields thereby avoiding the leaking of its views .So now the context will live as long as the application is alive. 
@chhavip @anubhakushwaha @aanchal07  Please review the PR.
_Thank you_
=> Fixes #321 :Memory leak issue in some part of code

PowerUp/app/src/main/res/layout-land/activity_select_features.xml
Linear Layout background colors updated which showed inconsistency on orientation change.
=> Colors updated for landscape linear layout

PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java, PowerUp/app/src/main/res/layout-land/activity_select_features.xml
PR for #282 
Changes:
- Store items state saved on orientation changed
- Combined the on click listeners of all store items thereby reducing lines of code by approx 120 lines.
- in the land-layout xml added continue text on the continue button so that it is visible on orientation change.
=> Fix:Store state saved on orientation changed

PowerUp/app/src/main/java/powerup/systers/com/DressingRoomActivity.java, PowerUp/app/src/main/res/layout-land/dressing_room.xml, PowerUp/app/src/main/res/layout/dressing_room.xml
Fixes #311 
I have fixes the following things in DressingRoomActivity:
1)So after selecting the clothes in DressingRoomActivity ,user presses the continue button to change the avatar.Now if we press **"back"** button (two times) to return to the DressingRoomActivity ,avatar shown is updated one(i.e.  there is no need to change the device orientation in order to see the changes).
2)Fixes the similar case while selecting **hairs** and **accessories** option.
3)Added the ImageViews **bag,glasses,hat and necklace** in dressing_room.xml in landscape mode(earlier that views were absent) in orderto make the changes consistent in landscape mode too.
@chhavip @aanchal07 @anubhakushwaha Please review this PR.
_Thank You_
=> Fixes#311:Multiple bugs in DressingRoomActivity

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java
=> Solved Abrupt opening of GameOver and wrong order of scenarios

PowerUp/app/src/main/assets/Answer.csv, PowerUp/app/src/main/assets/Question.csv, PowerUp/app/src/main/assets/Scenario.csv, PowerUp/app/src/main/res/layout/game_activity.xml
Adds hospital scenario as suggested in #385
=> Adds Scenarios to the Game

PowerUp/app/src/main/assets/Answer.csv, PowerUp/app/src/main/assets/Question.csv, PowerUp/app/src/main/assets/Scenario.csv, PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/res/values/strings.xml
Adds the Home-2 scenario, the consent scenario.
=> Adds Home-2 Scenario 

PowerUp/app/src/main/java/powerup/systers/com/GameOverActivity.java, PowerUp/app/src/main/res/layout-land/completed_game.xml
=> Adds Buttons to Completed Game Screen

PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java
Resubmit of PR #415 addressing issue #402
=> Resubmit: Added functionality to Home button of game map

.travis.yml, PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/res/layout-land/game_activity.xml
=> Fixed whitespace in listview (#441)

PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimGame.java
Solved the Animation bug in Sink to Swim Game - Boat sometimes doesn't come up with the correct answer.
=> Solved the Animation bug in Sink to Swim Game

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimGame.java, PowerUp/app/src/main/res/layout/activity_sink_to_swim_game.xml, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/SinkToSwimTests.java
@aanchal07, I have added a temporary continue button which was necessary for writing the tests. I will replace this continue button by Tutorials in next PR.
=> Adds Unit tests for Sink to Swim Game

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java, PowerUp/app/src/main/res/layout-land/avatar.xml, PowerUp/app/src/main/res/layout-land/avatar_room.xml
The final avatar screen has been updated with new UI designs.
=> Updates the Final Avatar Screen with new Designs

README.md
=> Fixed typo in README.md.

PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java, PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
This Pull request adds New store activity and required changes -
1. The database has been modified - Some utility functions in DBHandler class related to telepathy and health powers are deleted. Also, since now we have one accessory at a time, I have changed the Avatar Entry Table by removing the COLUMN_BAG and adding the COLUMN_ACCESSORY. This column will keep account of currently set accessory to the avatar. 
This was needed because now we can have many accessories i.e. They won't be just limited to the bag, necklace, etc. That's why we can't have separate columns for each accessory. I made a general column i.e. COLUMN_ACCESSORY for them.
2. I have made changes to .csv files which are used to fill database for the first time. Since accessories model is changed and quantity of new items …
=> Modifies Database and Adds Store Activity

PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java, PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
Earlier the accessories were not shown in Game activity. It has been done now !!
=> Updates the Avatar in Game activity with Accessories

PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java
=> Fix Initial settings bug

PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
Fix issue https://github.com/systers/powerup-android/issues/597.
In game screenshots:
=> Rearrange Store Items 

PowerUp/app/src/main/java/powerup/systers/com/GameOverActivity.java, PowerUp/app/src/main/res/layout-land/completed_game.xml
GameOverActivity displays Karma points as is shown in ScenarioOver Activity.
=> Show Karma Points

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/res/values/strings.xml
Pull Request as part of the GCI'17 task 'Fix the home button in PowerUp Android
Fixes # [ISSUE]
https://github.com/systers/powerup-android/issues/725
=> Program GCI: Fix Home Button

PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java
Handle the implementation of Next and Previous Arrows for Store activity. Remove listener conditional as it's not needed if the button is gone  in the first place
- Code
Screenshots of the arrows visibility.
If the number of item is less than 7 (only 1 page).
First page
Last page
=> Implementation of Next and Previous Arrows 

PowerUp/app/src/main/java/powerup/systers/com/minesweeper/MinesweeperGameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimGame.java, PowerUp/app/src/main/java/powerup/systers/com/vocab_match_game/VocabMatchGameActivity.java
I squashed the commits I made into one commit. I had to make a new branch and PR so I am closing the previous PR
=> Program:GCI Add mini game score to total karma points

PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java
Pull Request as part of the GCI'17 task 'PowerUp Android: Rectify the implementation of Green Tick in Store'
- #### Fixes #881 
- Code
- Debug Run, Screenshot attached.
=> Program: GCI Green Tick Correct Implementation

PowerUp/app/src/main/res/layout/simplerow.xml
Added ripple effect for game list view items
=> Program GCI: Add Ripple effect on selecting dialogue

PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java
Animation is supported on all API levels
=> Program GCI: Add transition animation in Store Activity

PowerUp/app/src/main/java/powerup/systers/com/vocab_match_game/VocabMatchGameActivity.java
Increased the time for color change animation in Vocab Game by increase value of delay millis to make that function wait for a particular time.
=> Increase the time for colour change animation in Vocab Game

PowerUp/app/src/main/java/powerup/systers/com/db/AbstractDbAdapter.java, PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimGame.java
Pull Request as part of the GCI'17 task 'Lint issue(Part I): Remove probable bugs from PowerUp Android'
Fixes #588
=> Program GCI: Fixing Lint Error Part 1

PowerUp/app/src/main/res/layout-land/avatar_room.xml
correct background shown in AvatarActivity
=> Program:GCI Avatar background fixed

PowerUp/app/src/test/java/powerup/systers/com/powerup/test/AboutActivityTest.java
Add `AboutActivityTest` for improving code coverage. The added class tests `AboutActivity` using _Robolectric_.
- Code
Before adding test, the test coverage was:
After adding test, the test coverage is:
=> Add AboutActivityTest for improving code coverage.

PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MapActivityTests.java
I've improved code coverage percentage by creating tests for MapActivity. I created 6 tests to check different behaviors features.
**Before:**
**After**:
As you can see I increased Code Coverage Percentage of MapActivity from 0 to 87 percents.
**Screenshot of successful pass:**
=> Program GCI: Improve code coverage

PowerUp/app/src/main/res/values-v11/styles.xml, PowerUp/app/src/main/res/values-v14/styles.xml, PowerUp/app/src/main/res/values/styles.xml
Reverts systers/powerup-android#959
=> Revert "Reducing Overdraw by removing app background"

PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java
=> fix : semi-colon missing in StartActivity

.travis.yml, PowerUp/app/build.gradle, PowerUp/build.gradle, PowerUp/gradle/wrapper/gradle-wrapper.properties
Fixes false positives for travis.
Fixes #491
=> Fix travis

.travis.yml, PowerUp/app/build.gradle
Fixed gradle dependencies such that the layout preview is available
Fixes #1051 
- Code
The code has been tested on Android Studio emulator
=> Fix gradle dependencies

README.md
Changed the name of the branch that contains the latest code from "GSOC17" to "develop" .
Fixes # [1068]
- Documentation
This change has been verified by comparing with the previous README.md.
=> Fixes #1068 README.md is now updated

PowerUp/app/build.gradle, PowerUp/build.gradle
It includes variables for dependency version. 
Fixes #1062 
Since , it has only changed gradle files. I've rebuilt the project & Gradle build it sucessfully. 
-- [ ] I have performed a self-review of my own code or materials
=> fix #1062 : shifted depency version to variables

PowerUp/app/src/main/java/powerup/systers/com/SplashActivity.java
Remove handler callbacks on calling onDestroy
Fixes #1032
- Code
Checked the Logcat when the app is running
=> Fix memory leak in SplashActivity

.travis.yml, generate-apk.sh
Automates the apk building process.
Fixes #1106
- Infrastructure and automation
=> Automate the process of updating the apk

PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java
Fixes #797 
- Code
I've tested it on my API 22 genymotion virtual device
Slack discussion link: [thread1](https://systers-opensource.slack.com/archives/C0C9VK8UE/p1521435272000034) & [thread2](https://systers-opensource.slack.com/archives/C08C83YLQ/p1522326825000331)
=> fix default eyes

PowerUp/app/src/main/assets/Answer.csv
The PR contains modifications to Answer.csv such that Home Scenario ends after the user chooses "Remains Quiet"
Fixes #969
- Code
The code change is tested on Android Studio emulator.
=> Fixes #969 Database error in home scene

.travis.yml, generate-apk.sh
Update apk only when travis build is successful
Fixes #1118
=> Update apk only when travis build is successful.

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java
Changes have been made to onBackPressed() such that when the back button is pressed on android device, the user is presented a warning dialog similar to on pressing home button.
Fixes #996 
- Code
The changes have been tested on Android Studio emulator.
=> Fixes #996 Warning dialog when back button is pressed

PowerUp/app/src/main/assets/Answer.csv
The karma points are rearranged in a way to provide proper functionality to progress bars and mini games, such that,
1 Karma Point  -> Bad response
2,3 Karma Point -> Average response
4 Karma Point -> Good Response
Fixes #1044 
- Code
The changes have been tested on Android Studio emulator
=> Fixes #1044 Redistribution of karma points

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java
Using static variable "hasPreviouslyCustomized", declared in SessionHistory.java with a default value of false to check if the variable was previously customized by the user.
The variable also changes to false whenever the user chooses "NEW GAME" such that the avatar resets to default values.
The if else block in AvatarRoom.java checks is the user has previously changed the default values or not and updates the avatar accordingly. 
Fixes #997 
- Code
The code has been tested on Android Studio emulator.
=> Fixes #997 avatar now sets to default values

PowerUp/app/src/main/java/powerup/systers/com/utils/CSVReader.java
As a developer, I wanted to separate CSV reading from database file. 
It'll read from CSV & return the List of entity class as expected. 
Fixes #1123 
- Code
Gradle builds successfully though It hasn't been tested yet.
=> created csvreader util file

.travis.yml, PowerUp/app/build.gradle, PowerUp/app/src/main/res/drawable/btn_bg.xml, PowerUp/app/src/main/res/layout-land/activity_pregame_setup_initial_screen.xml, PowerUp/app/src/main/res/values-land/dimens.xml, PowerUp/app/src/main/res/values/color.xml, PowerUp/app/src/main/res/values/dimens.xml, PowerUp/app/src/main/res/values/strings.xml, PowerUp/build.gradle, PowerUp/gradle.properties, PowerUp/gradle/wrapper/gradle-wrapper.properties
Added initial screen for PreGame Setup. 
Fixes #1134 
- Code
=> Created initial screen for pregame setup

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/FinalAvatarActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameOverActivity.java, PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java, PowerUp/app/src/main/java/powerup/systers/com/SplashActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java, PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java, PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimGame.java, PowerUp/app/src/main/res/values/strings.xml
PR contains comments for class files to help understand the code easily:
* SplashActivity
* StartActivity
* AvatarRoomActivity
* FinalAvatarRoomActivity
* MapActivity
* GameActivity
* GameOverActivity
* StoreActivity
* SinkToSwimGame
Fixes #1130  
- Documentation
Gradle builds successfully. 
=> comments added in different class files

PowerUp/app/src/main/res/layout-land/game_activity.xml
Modified the game activity to contain correct npc that can be changed from game activity dynamically depending on user's choice.
Fixes #1135 
- Code
=> Modify game activity

PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java
Removes non-functional code from StartActivity.java. 
Deleted overridden onResume() function.
Fixes #1143 
- Code
Successfully ran on an android device.
=> Fixes #1143 Removed unnecessary code from StartActivity.java

PowerUp/app/src/main/java/powerup/systers/com/data/DataSource.java, PowerUp/app/src/main/java/powerup/systers/com/data/IDataSource.java, PowerUp/app/src/main/java/powerup/systers/com/data/dao/AccessoryDao.java, PowerUp/app/src/main/java/powerup/systers/com/data/dao/AnswerDao.java, PowerUp/app/src/main/java/powerup/systers/com/data/dao/QuestionsDao.java, PowerUp/app/src/main/java/powerup/systers/com/data/dao/ScenarioDao.java, PowerUp/app/src/main/java/powerup/systers/com/data/entities/Scenario.java
This PR contains the following changes:
Fixes #1138
- Code
Gradle builds successfully but functions haven't been tested yet.
=> Datasource file created & impvroved Dao function

PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java
Implementation of warning dialog such that the item selected by the user apperas ion the Avatar only if she decides to purchase it
Fixes #998
- Code
The changes were checked in android studio emulator
=> Fixes #998 Rectify implementation of warning dialog

PowerUp/app/build.gradle, PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/LeakCheckApplication.java
fixes #664 
**Description**
LeakCanary incorporated in the application to detect memory leaks  easily and time efficiently.
To detect leaks, add the code given below in the onDestroy method of the activity - 
```
RefWatcher refWatcher = LeakCheckApplication.getRefWatcher(this);
refWatcher.watch(this);
```
=> LeakCanary Added to detect Memory Leaks

PowerUp/app/build.gradle, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java, PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PreGameSetupInitialActivity.java, PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PregameSetupActivity.java, PowerUp/build.gradle
Included logic such that the NPCs in the respective scenarios are updated according to user's choice.
I have also fixed the UI error for ticks.
Fixes #1152 
- Code
Sister in Home Scenario
Friend in School scenario
Doctor in School scenario
Teacher in Library scenario
=> Update game activity to include proper NPCs

PowerUp/app/src/main/java/powerup/systers/com/pregame_setup/PregameSetupActivity.java, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/PregameSetupActivityTest.java
Adding tests for PreGameSetupActivity
Fixes #1155 
- Code
=> Adding tests for PreGameSetupActivity

PowerUp/app/src/test/java/powerup/systers/com/powerup/test/PreGameSetupInitialActivityTest.java
Added test for initial activity of PreGame setup. 
Fixes #1154 
- Code
=> Added tests for initial activity of PreGame setup

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/KillTheVirusTutorialTest.java
I have added tests for tutorial screen of the mini game.
Since the functionality mainly concerns with changing the values of alpha, the only value that could be checked was the global variables. The logic is described in the working doc: https://docs.google.com/document/d/19WiSVkcxl6zx0kzMviKPA7-A1fs7XRzSaDKbpgN1IZ0/edit?usp=sharing
In KillTheVirusTutorials.java only the views are initialized and the functions are defined with TODO tags. The actual code will be added durong development of the logic.
Fixes #1181 
- Code
=> Adding JUnit tests for tutorial screens

PowerUp/app/src/main/res/layout-land/activity_memory_match_tutorial.xml, PowerUp/app/src/main/res/values/dimens.xml, PowerUp/app/src/main/res/values/strings.xml
I have added xml layout for the tutorial of the mini game.
It contains three text views, viz. , txt_memory_tutorial_1, txt_memory_tutorial_2, txt_memory_tutorial_3 to give proper instructions to the user before starting the game.
I have used tag to have a proper background of mini game, that adapts properly to the screen, when the textviews are shown.
The logic I am planning to use here is change the value android:alpha to change the visibility of the design elements according to the tutorials that I will implement during coding.
Fixes #1187 
The current view of the xml file is:
After modifications the screen would show three different tutorial texts on …
=> Added tutorial screens for Memory Match game

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java, PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java, PowerUp/app/src/main/res/animator/translate.xml, PowerUp/app/src/main/res/drawable/arrow_kill.xml, PowerUp/app/src/main/res/values/array.xml, PowerUp/app/src/main/res/values/strings.xml, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/KillTheVirusGameTest.java
I have added functionality to main screen of mini game 1.
1.  Circular Rotation of Virus -> Use ValueAnimator
- initializeViews() - sets ValueAnimator on all the images of the virus using animateVirus()
2. Update the color of syringe( currently a rectangular view is used as place holder) after each click
- hitCount - a count variable to count the number of hits ranging between 0 and 3
- After each click on the screen handled by clickScreen() the value of hitCount is increased and the color of the view is updated accordingly
3. Match the color of virus with that of syringe
- Using an if-else block inside checkHit() the virus that was intended to be clicked is identified using getAnimateValue() function
- If color of the view matches the color of the virus rightHit() is called otherwise …
=> Added functionality to main screen of mini game 1

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java, PowerUp/app/src/main/res/layout-land/activity_memory_match_game.xml, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchGameTest.java
The tests are written to test the logic followed as described on the working doc. The tests fail currently since the working code is not yet developed and the variables are not initialized
clickYesTest() -- The logic that is tested here is if yes is pressed then the tile values in arrayTile1 and arrayTile3 should be same for getting the answer to be correct
clickNoTest() -- The logic that is tested here is if no is pressed then the tile values in arrayTile1 and arrayTile3 should not be same for getting the answer to be correct
correctAnswerTest() -- The test assumes a case for correct answer and checks if the values are updated propery
wrongAnswerTest() -- The test assumes a case for wrong answer and checks if the values are updated propery
updateArrayTest() -- The test checks if the …
=> Added JUnit tests for main screen of memory match"

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchTutorialActivity.java, PowerUp/app/src/main/res/layout-land/activity_memory_match_tutorial.xml, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchTutorialTest.java
I have added tests for tutorial screen of the mini game.
Since the functionality mainly concerns with changing the values of alpha, the only value that could be checked was the global variables. The logic is described in the working doc: https://docs.google.com/document/d/19WiSVkcxl6zx0kzMviKPA7-A1fs7XRzSaDKbpgN1IZ0/edit?usp=sharing
In MemoryMatchTutorialActivity.java only the views are initialized and the functions are defined with TODO tags. The actual code will be added during development of the logic.
Fixes #1193 
- Code
=> Added JUnit tests for tutorial screen of Memory Match

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchEndActivity.java, PowerUp/app/src/main/res/layout-land/activity_memory_match_end.xml, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchEndTest.java
For now, I have just defined and initilaized the files.
Since the activity does not do any major changes and only updates the views, the only test that could be added would be check the points that are stored in the preference manger.
This could be done only after whole game is developed so the file does not containing any tests presently.
Fixes #1195 
- Code
The project builds successfilly on my machine
=> Added JUnit tests for end screen of mini game 2

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/KillTheVirusGameTest.java
I have modified some test cases after developing the actual code.
Since the activity majorily has imageviews and animation, I could only add some assertion tests using JUnit.
Fixes #1201 
- Code
All the tests pass successfully on my machine.
=> Added tests for main screen of mini game 1

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java, PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchTutorialActivity.java, PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java, PowerUp/app/src/main/res/animator/translate_tile.xml, PowerUp/app/src/main/res/layout-land/activity_memory_match_game.xml, PowerUp/app/src/main/res/values/strings.xml, PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchGameTest.java
I have added functionality to Memory Match Game and have also modified the tests to check the logics.
The main idea of the game is to show a number of pictures on the leftmost tile of the screen that sweeps to it's immediate right tile on each round. The user needs to press "Yes" or "No" depending on whether the picture that is in the leftmost position of the screen matches the picture that is hidden under the rightmost tile.
Coding logic is:
- All the tiles with their unique ids are stored in an array named MEMORY_GAME_TILE
- An arraylist named arrayTile is  used to store the indices of all the tiles that are displayed on the screen randomly
- Since the user needs to match the tile that is shown on the screen and the tile that appeared one tile before it the values at positionCount and …
=> Adding functionality to the main screen of Memory Match

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java, PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java, PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_game.xml, PowerUp/app/src/main/res/values/strings.xml
I have modified the virus game such that:
- speed of rotation is increased after every right/wrong hit using function updateSpeed()
- there are 3 lives that is handled through updateLives()
Fixes #1216 
- Code
Currently there is no direct option to trigger the mini game.
One way to launch it is by changing line 116 of StartActivity.java from
```  startActivity(new Intent(StartActivity.this, AboutActivity.class)); ```
to 
```  startActivity(new Intent(StartActivity.this, KillTheVirusTutorials.class)); ``` 
and then using ABOUT button on the main screen of app to launch the game. …
=> Added modifications to kill the virus game

PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchEndActivity.java, PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java
The code updates the values of score, number of correct answers and number of wrong answers that are passed as intent extras.
Fixes #1212 
- Code
- Outreach
- Documentation
- This change requires a documentation update (software upgrade on readme file)
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
=> Functionality to the end screen of memory match

PowerUp/app/src/main/res/layout/activity_save_the_blood_game.xml, PowerUp/app/src/main/res/values/dimens.xml, PowerUp/app/src/main/res/values/strings.xml
In this PR I have defined the basic layout for main scren of mini game 3 - save the blood.
Fixes #1236 
Currently there is no way to launch the screen since the PRs for level 2 have not been merged yet.
=> Added main screen for mini game 3

PowerUp/app/src/main/AndroidManifest.xml, PowerUp/app/src/main/java/powerup/systers/com/MapLevel2Activity.java, PowerUp/app/src/main/java/powerup/systers/com/StoreLevel2Activity.java, PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
The PR has modified version of store activity for level 2 such that the design elements fit the high school version. I defined two new arrays in PowerUpUtils.java to hava clothes for level 2 that can be selected from store.
The is an UI in gridview of clothes in store activity since the elements require resizing to fit the item. 
Fixes #1213 
- Code
Level 2 canbe launched after completion of Level 1.
=> Store level 2

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java, PowerUp/app/src/main/java/powerup/systers/com/GameLevel2Activity.java, PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java, PowerUp/app/src/main/res/layout-land/activity_game_level_2.xml, PowerUp/app/src/main/res/layout-land/game_activity.xml
In this PR I have added four progress bars to the game activity. The main purpose of the progress bars is to reflect the quality of answers user chooses. The quality of answers is reflected by the points given for a particular answer.
updateProgressBars() is used to update the progress bars after each answer is chosen. The value fo progress for invisibility and telepathy continuously increase depending on the points for a chosen answer. The value of health and healing decrease if the point is 1 that shows a bad choice, otherwise increase. If value of a progress bar reaches maximum, that is, 100 5 extra karma points are given to the user and the progress bar again starts from 0.
When the progress bars reaches a maximum value it turns green and becomes cilckable.
showDialog() is used to …
=> Added functionality to progress bars

PowerUp/app/src/main/res/layout-land/completed_game.xml, PowerUp/build.gradle
I attached a click listener to map button to ensure that backToMapListener() is called everytime map button is clicked.
Fixes #1263
- Code
=> Map button fix

PowerUp/app/src/main/java/powerup/systers/com/ui/store_screen/StoreActivity.java, PowerUp/app/src/main/java/powerup/systers/com/ui/store_screen_level2/StoreLevel2Activity.java
In this PR, I have hardcoded values  to use values from PowerUpUtils.
Fixes #1273 
- Code
The app runs as before on android studio emulator.
=> Replaced constants in StoreActivity

PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java
Enhanced the UI to respond to correct and wrong answers.
Fixes #1280 
- Code
=> UI enhancement to Memory Match Game

PowerUp/app/src/main/java/powerup/systers/com/data/DataSource.java
As specified in the issue, the error was in the DataSource file. Clicking on first accessory now, presents the warning dialog.
The changes would be visible better after #1279 is merged.
Fixes #1274 
- Code
The changes can be reproduced by selecting the first accessory in store. 
=> Fixed accessory selection at store
