systers/powerup-android

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoom.java

Fixed the crash on selecting a new avatar in AvatarRoom , specifically on pressing the continue button, as a closed database was being accessed. Error Log in image.

closed db was being accessed, fixed #6

---

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java

Fixed #29 , Map Activity opened after user chooses an avatar

Open map activity after change room

---

PowerUp/app/src/main/AndroidManifest.xml
PowerUp/app/src/main/java/powerup/systers/com/CompletedScene.java
PowerUp/app/src/main/java/powerup/systers/com/Game.java

Fixed #23 . Finished activities to remove them from stack and take back directly to map. Also made map a singleTop launch activity so that multiple instances of the same activity are not launched.

fixed back to map and navigation issues

---

PowerUp/app/src/main/java/powerup/systers/com/AvatarActivity.java
PowerUp/app/src/main/java/powerup/systers/com/AvatarRoom.java

Fixed #32 . The change room has been removed from back stack, avatar room(with options) is maintained while on confirmation screen so that changes can be made till the last moment before moving  on to the map.

Removed change room from back stack

---

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java

Clicking on the replay button on the GameActivity.java again started GameActivity.java via an Intent. Thus GameActivity.java was stacked twice and we had to click the back button two times to return to the MapActivity.java. Similarly for goToMap button we had to press back button twice to return to StartActivity.java.
Fixed the problem by popping the stack top with button click.

Removed Backstack from replay and goToMap buttons.

---

PowerUp/.gitignore

This modified version of .gitignore is widely accepted and practised.
Source:
http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project
Fixes issue #130

.gitignore modified to match a standard .gitignore

---

PowerUp/app/src/main/java/powerup/systers/com/AboutActivity.java
PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java

Fixes #282 
@chhavip @aanchal07 @anubhakushwaha Changes made are as follows -
1. For About Activity - Added boolean variables isAboutGameOpen, isAboutUrgencyOpen and  isAboutHelpingOpen which will retain the state of Textview in saveInstanceState. 
Other than this, Textview needed to be made global so as to access them in onCreate().
2. For Game Activity - If the orientation is changed, activity is recreated and savedInstanceState is not null. Thus in this case, we can keep the question same as last question in SessionHistory.
Please review. Thanks :-)

Fix Orientation Issues in About and Game Activity

---

PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java
PowerUp/app/src/main/res/layout/activity_main.xml
PowerUp/app/src/main/res/values/strings.xml

PR for #279 
For the above change I made the following changes:
- added resume text in strings.xml.
- set`android:textStyle="bold"`to bold in activity_main.xml
- used `boolean hasPreviouslyStarted` to determine weather gameplay has started or not.

Fix: Changed start button to resume during gameplay

---

PowerUp/app/src/main/java/powerup/systers/com/db/DatabaseHandler.java

This allows the avatar to be correctly displayed in `AvatarActivity`.

Use the correct indices to access columns in the Avatar table

---

PowerUp/app/src/main/java/powerup/systers/com/DressingRoomActivity.java
PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java

Fixes #281 
Bugs solved - 
1. As shown below, earlier on pressing back in final avatar screen, user can go back to selection screen - I have solved this by taking user to main screen on pressing back thereby restricting to reedit the selection. (Using Intent.FLAG_ACTIVITY_CLEAR_TOP)
2. Above, as we can see points were not updated on pressing back because - After pressing back control enters onResume of activity and shows old score on even Main Screen. I have solved this by updating score in onResume.
3. For Hair, Bag, Glasses, and Necklace, the points deducted were always wrong. I have solved this by rectifying some mistakes. (Earlier it was deducting points of clothes for Hair AND Points of Hat for Bag/Glasses/Necklace)
4. Sometimes the Karma score went negative though should not be …

Fix Multiple Bugs in Karma Points System in Store

---

PowerUp/app/src/main/res/layout-land/avatar.xml
PowerUp/app/src/main/res/layout-land/avatar_room.xml
PowerUp/app/src/main/res/layout/activity_select_features.xml
PowerUp/app/src/main/res/layout/avatar.xml
PowerUp/app/src/main/res/values-large/dimens.xml
PowerUp/app/src/main/res/values-xlarge/dimens.xml
PowerUp/app/src/main/res/values/dimens.xml

Fix #326 
The Accessories Dressing room now supports all screen sizes. The tweaks made are -
Added some linear layouts around selection boxes with layout_weight property so they can adjust to any screen size. To scale them properly for big screen sizes, I have created 2 dimens.xml files - large and x-large. 
Nexus One 
I have tested it on Nexus One, Nexus S, Nexus 4, Nexus 4X, Nexus 5, Nexus 5X, Nexus 6, Nexus 6p, Nexus 9, Nexus 10 (tablet), MotoX Style, Galaxy Nexus, Pixel C, Pixel XL and many more devices. It working fine on all these devices.

Added support for all screen sizes for Dressing Room

---

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java
PowerUp/app/src/main/java/powerup/systers/com/SelectFeaturesActivity.java

Fix #371 , items chosen for new player are shown as "PAID" in store.

Intial Possessions of Avatar reflected in Store now

---

PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java
PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java
PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimEndActivity.java

I used the existing ScenarioOver screen, just add an extra intent parameter to handle final scenario continue button navigation.

Program GCI: Include a Scenario Over Screen after Library scenario

---

PowerUp/app/src/main/res/values-v11/styles.xml
PowerUp/app/src/main/res/values-v14/styles.xml
PowerUp/app/src/main/res/values/styles.xml

I reduced overdraw of the app by setting the default background to null.
Attached please find the report:
[Reducing Overdraw.docx](https://github.com/systers/powerup-android/files/1633764/Reducing.Overdraw.docx)

Reducing Overdraw by removing app background

---

PowerUp/app/src/test/java/powerup/systers/com/powerup/test/AboutActivityTest.java
PowerUp/gradle.properties

Robolectric tests fails in Android studio 3.0+. It requires to have aapt2 disabled to successfully run the tests. Also , This PR imports a os.build (Fixing GCI PRs )
Fixes #1033 
Unit tests run successfully after changes made.

fix #1033 failing tests

---

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java

Implementation of home button is fixed such that it doesnot disappear after presseing cancel on warning dialog
Fixes #1006 
- Code
The changes have been tested on Android Studio emulator

Fixes #1006 Cancel option in warning dialog

---

PowerUp/app/src/main/res/values-land/dimens.xml

Changes made in dimen.xml, in "about_text_size_section_title" it has been changed as sp - "scale-independent-pixels" instead of dp.
Fixes #534 
- Code

Usage of "dp" for text size

---

PowerUp/app/src/main/java/powerup/systers/com/StoreActivity.java

A method getselectedItemId() is included in place of variable selectedItemId to correctly identify and distinguish among hair, clothes and accessories and set the ticks accordingly.
Fixes #1000
- Code
The changes have been tested on Android Studio emulator.

Fixes #1000 Green tick implementation

---

PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java

An if statement is add before the deduction of karma points in ScenarioOverActivity.java
``` 
if(SessionHistory.totalPoints - SessionHistory.currScenePoints >= 0)
SessionHistory.totalPoints -= SessionHistory.currScenePoints; 
```
The major purpose of if statement is that the karma points will be deducted only if deduction does not gives rise to a negative value
Fixes #524 
- Code
The changes have been tested on android studio emulator

Fix #524 Negative karma points

---

PowerUp/app/src/main/res/layout/activity_sink_to_swim_game.xml
PowerUp/app/src/main/res/values/strings.xml

Initially when the game starts the score in the game is diaplyed with two digits,that is, two zeros.
But just after first response from the user, the score is displayed with just one digit.
If the user pressed the skip button or the answer by the user is wrong, the double digit of the score,that is, double zeros of the score are set to a single zero.
If the user answers correctly, the double zeros are set to a single one.
Fxed the issue by adding relevant string resource.
Fixes #530 
- Code
Ran the app again on Redmi Note 4 to verify the UI change.

Fixes #530 Inconsistent display of score

---

PowerUp/app/src/main/java/powerup/systers/com/sink_to_swim_game/SinkToSwimGame.java

Initially, the transition timings of questions in minigame SinkToSwim were quite slow. Through this PR, I have tries to reduce the animation transition timings to enhance the UX.
Fixes #523 
- Code
- This change requires a documentation update (software upgrade on readme file)
Refer to GIF here (Though it might appear a bit slow): 
https://user-images.githubusercontent.com/26908195/31807843-006472d8-b58e-11e7-994b-9d497b8eb98f.gif
Steps to Reproduce:
1. Press True button in SinkToSwim game
2. Press False button in SinkToSwim game
3. Press Skip button in SinkToSwim game

Reduced transition timings of questions in SinkToSwim minigame

---

PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java

The PR contains changes such that the total points dialog on Scenario Over screen appears only if it is lauched after scenario completion and not from map.
Fixes #999 
- Code
The changes have been tested on android studio emulator

Fixes #999 Appearance of total points dialog

---

PowerUp/app/src/main/java/powerup/systers/com/AvatarRoomActivity.java
PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java
PowerUp/app/src/main/java/powerup/systers/com/ScenarioOverActivity.java
PowerUp/app/src/main/java/powerup/systers/com/datamodel/SessionHistory.java
PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java

Rectified the handling of replay button such that correct scene is launched after clicking the replay button.
An intent extra with the name of the scenario clicked on the map is passed to ScenarioOverActivty.
With the help of switch case block the scenario which was clicked on is identified and that particular scenario is launched accordingly.
Boolean variables sceneHomeIsReplayed, sceneSchoolIsReplayed, sceneHospitalIsReplayed and sceneLibraryIsReplayed are defined in SessionHistory.java which is set to true if the clicked upon scenario is already played and is replayed. The basic utility of variables is to take care that the next scene in the queue does not get grayed out on map if the selected scene to be replayed is left in the middle.
An if-else block:
```
if(getIntent().getExtras() …
```

Fixes #500 replay to launch correct scenario

---

PowerUp/app/src/main/res/layout-land/activity_memory_match_game.xml
PowerUp/app/src/main/res/values-land/dimens.xml
PowerUp/app/src/main/res/values/dimens.xml
PowerUp/app/src/main/res/values/strings.xml

Assws xml layout for main screen of mini game 2 - Memory Match.
The laoyout is designed according to the mocks shared earlier
Fixes #1188 
Currently there is not any code to launch the screen.
I have modified code to check it on my device.

Added layout for main screen of memory match

---

PowerUp/app/src/main/res/layout-land/activity_memory_match_end.xml
PowerUp/app/src/main/res/values/dimens.xml

I have added the game end screen for mini game 2 - Memory Match.
The screen contains 3 text views toshow total points scored, number of correct answers and number of wrong answers.
Fixes #1189 

Added end screen for memory match

---

PowerUp/app/src/main/res/drawable/btn_bg.xml
PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_tutorial.xml
PowerUp/app/src/main/res/values/dimens.xml
PowerUp/app/src/main/res/values/strings.xml

I have added xml layout for the tutorial of the mini game.
It contains three text views, viz. , txt_tutorial_1, txt_tutorial_2, txt_tutorial_3 to give proper instructions to the user before starting the game.
I have used <include/> tag to have a proper background of mini game, that adapts properly to the screen,  when the textviews are shown. 
The logic I am planning to use here is change the value android:alpha to change the visibility of the design elements according to the tutorials that I will implement during coding.
Fixes #1179 
Note: This is a rectification PR for #1180. I somehow deleted the commit while resolving the conflicts and was not able to push the commits so I made a new PR.
- Code
- New feature (non-breaking change which …

Add tutorials for kill the virus

---

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java

I have added functionality to the tutorial screen of mini game 1 such that all the tutorials are shown in proper sequence and then the game is started.
- Create a onClickListener() on whole layout so that the screen can be updated when touched anywhere
- Declare a count variable tutorialCount = 0, to change the alpha values of the design elements to make the proper tutorials visible
- The variables visiblie, notVisible and gone are used to set the value for alpha
- When tutorialCount is 0 first tutorial screen will be visible using function initializeViews()
- When tutorialCount is 1 second tutorial screen will be visible using function showTutorial2()
- When tutorialCount is 2 third tutorial screen will be visible using function showTutorial3()
- When tutorialCount is 3 -> intent …

Kill the virus tutorials

---

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusEndActivity.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
PowerUp/app/src/main/res/layout-land/activity_kill_the_virus_end.xml

I have added proper code so that scores are displayed properly
- The score is passed between activities using intent extra
- updateScore() retrives the value from intent extra
Currently, on pressing continue and back button StartActivity is launched since the mini game is not attached to any scenarios. I will update this when the new scenarios will be added.
Fixes #1207 
- Code
Currently there is no direct option to trigger the mini game.
One way to launch it is by changing line 116 of StartActivity.java from
```  startActivity(new Intent(StartActivity.this, AboutActivity.class)); ```
to 
```  startActivity(new Intent(StartActivity.this, …
```

Added functionality to end screen

---

PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchTutorialActivity.java
PowerUp/app/src/test/java/powerup/systers/com/powerup/test/MemoryMatchTutorialTest.java

I have added functionality to the tutorial screen of mini game 2 such that all the tutorials are shown in proper sequence and then the game is started.
- Create a onClickListener() on whole layout so that the screen can be updated when touched anywhere
- Declare a count variable tutorialCount = 0, to change the alpha values of the design elements to make the proper tutorials visible
- The variables visiblie, notVisible and gone are used to set the value for alpha
- When tutorialCount is 0 first tutorial screen will be visible using function initializeViews()
- When tutorialCount is 1 second tutorial screen will be visible using function showTutorial2()
- When tutorialCount is 2 third tutorial screen will be visible using function showTutorial3()
- When tutorialCount is 3 -> intent …

Added functionality to tutorial screen of Memory Match

---

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusSessionManager.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java
PowerUp/app/src/main/java/powerup/systers/com/powerup/PowerUpUtils.java

I have added KillTheVirusSessionManager.java to handle the case that if the mini game is left in the middle the states are saved and when it is relaunched, the values are initialized according to the saved ones.
- saveData() is used to save all the required values, that is, score, number of lives left, time left and speed of rotation 
- getScore(), getLives(), getTime() and getSpeed() are used to retrieve the saved values
Also, I have done some code modifications that reduced the number of lines of code and made it much simpler.
Fixes #1220 
- Code
Since this is just a use case that if the migrates out to map in the middle of the mini game, there is no way to check it right …

Added session manager for kill virus game

---

PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java
PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchSessionManager.java
PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchTutorialActivity.java

I have added MemoryMatchSessionManager.java to handle the case that if the mini game is left in the middle the states are saved and when it is relaunched, the values are initialized according to the saved ones.
- saveData() is used to save all the required values 
- The various get functions are used to retrieve the saved values
Fixes #1221 
- Code
Since this is just a use case that if the migrates out to map in the middle of the mini game, there is no way to check it right now since the map for level 2 is not yet developed.
All the values that are saved are checked through log messages.

Add session manager for memory match

---

PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java

Added the mechanism to prevent user from scoring extra points in MemoryMatch by continously pressing yes/no button.
This is implemented by disabling the yes and no buttons while the linear animation of the tile is started and enabling them again when the animation is over.
Fixes #1230 
- Code
- Bug fix (non-breaking change which fixes an issue
Currently, there is no direct option to trigger the mini-game.
One way to launch it is by changing line 116 of StartActivity.java from
```  startActivity(new Intent(StartActivity.this, AboutActivity.class)); ```
to 
```  startActivity(new Intent(StartActivity.this,MemoryMatchGameActivity.class)); ``` 
and then using ABOUT button on the main screen of app to launch the game.
**Delete irrelevant …

Fix the error in memory match

---

PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java

I have code to add the points scored in minigames to total scenario points.
Fixes #1234 
- Code
Right now there is no way to launch the mini games.
The mini games are attached to scenarios in previous PRs.

Adding mini game scores to total scores

---

PowerUp/app/src/main/res/layout/activity_save_blood_end.xml

In this PR I have added xml layout for completion screen of mini game 3.
Fixes #1239 
- Code
Currently there is no way to launch the screen since the PRs for level 2 have not been merged yet.

Add end screen for mini game 3

---

PowerUp/app/src/main/res/layout/activity_save_the_blood_game.xml
PowerUp/app/src/main/res/layout/actvity_save_blood_tutorial.xml
PowerUp/app/src/main/res/values/dimens.xml
PowerUp/app/src/main/res/values/strings.xml

In this PR, I have added xml layout for tutorial screen of mini game 3.
Right now it has text view. Later, I will modify it to show the textviews separately as implemented in previous mini games.
Fixes #1238 
- Code
Currently there is no way to launch the screen since the PRs for level 2 have not been merged yet.

Add tutorial screens for mini game 3

---

PowerUp/app/src/main/AndroidManifest.xml
PowerUp/app/src/main/java/powerup/systers/com/GameLevel2Activity.java
PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodGameActivity.java
PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodTutorialActivity.java
PowerUp/app/src/main/res/layout/activity_save_the_blood_game.xml
PowerUp/app/src/main/res/layout/actvity_save_blood_tutorial.xml
PowerUp/app/src/test/java/powerup/systers/com/powerup/test/SaveTheBloodTutorialTests.java

I have added functionality to the tutorial screen of mini game 3 such that all the tutorials are shown in proper sequence and then the game is started.
- Create a onClickListener() on whole layout so that the screen can be updated when touched anywhere
- Declare a count variable tutorialCount = 0, to change the alpha values of the design elements to make the proper tutorials visible
- The variables visiblie, notVisible and gone are used to set the value for alpha
- When tutorialCount is 0 first tutorial screen will be visible using function initializeViews()
- When tutorialCount is 1 second tutorial screen will be visible using function showTutorial2()
- When tutorialCount is 2 third tutorial screen will be visible using function showTutorial3()
- When tutorialCount is 3 -> intent …

Add functionality to tutorial screens of memory match

---

PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodGameActivity.java
PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodSessionManager.java

I have added SaveBloodSessionManagerr.java to handle the case that if the mini game is left in the middle the states are saved and when it is relaunched, the values are initialized according to the saved ones.
- saveData() is used to save all the required values
- The getter functions are used to retrieve the saved values
Fixes #1250 
- Code
Since all the files related to mini game 3 are not yet merged, I have not attached the session manager to the mini game and there isn't anyway to check it.

Added session manager for mini game 3

---

PowerUp/app/src/main/AndroidManifest.xml
PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodEndActivity.java
PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodGameActivity.java
PowerUp/app/src/main/res/layout/activity_save_blood_end.xml

The PR adds functionality to game completion screen such that,
- Values of score and number of correct and wrong answer is passed on from game main screen to end screen
- The screen appears after main screen
- Pressing continue launches scenario completion scenario
Fixes #1245 
- Code
The screen can be launched after completion of the mini game

Added functionality to game completion screen of mini game 3

---

PowerUp/app/src/main/java/powerup/systers/com/GameLevel2Activity.java
PowerUp/app/src/main/java/powerup/systers/com/MapLevel2Activity.java
PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusEndActivity.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusGame.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusSessionManager.java
PowerUp/app/src/main/java/powerup/systers/com/kill_the_virus_game/KillTheVirusTutorials.java

In this PR, I have attached session manager to mini-game. The logis here is if the mini game was left in middle it is considered as still open and the value is set accordingly in saveKillTheVirusOpenedStatus(). Additionally, the values of all the variables in onPause().
Now when a scenario is clicked, first it is checked whether the mini-game was saved as open or not using isKillTheVirusOpened(). If it was opened first the mini-game is launched and all the variables are set according to the values stored in shared preferences.
Fixes #1252
- Code
The functionality can be tested by leaving the mini game …

Attached session manager in Kill the Virus

---

PowerUp/app/src/main/res/layout-land/activity_game_level_2.xml
PowerUp/app/src/main/res/layout-land/game_activity.xml

I have replaced the use of relative layout in game activity of level 1 and 2 to constraint layout so that placing of other elements become much easier. All the widths, heights and margins remain the same. This has also reduced the number of lines of code.
Fixes #1260 
- Code
The appearance of the screen is still the same as it was before.
Before
After

Changed the xml layout for game activity to constraint layout

---

PowerUp/app/src/main/java/powerup/systers/com/GameActivity.java
PowerUp/app/src/main/java/powerup/systers/com/MapActivity.java
PowerUp/app/src/main/java/powerup/systers/com/StartActivity.java
PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchEndActivity.java
PowerUp/app/src/main/java/powerup/systers/com/memory_match_game/MemoryMatchGameActivity.java

In this PR, I have attached session manager to mini-game. The logic here is if the mini game was left in middle it is considered as still open and the value is set accordingly in saveSinkToSwimOpenedStatus(). Additionally, the values of all the variables in onPause().
Now when a scenario is clicked, first it is checked whether the mini-game was saved as open or not using isSinkToSwimOpened(). If it was opened first the mini-game is launched and all the variables are set according to the values stored in shared preferences.
Fixes #1252
- Code
The functionality can be tested by leaving the mini game in …

Added session manager to Memory Match

---

PowerUp/app/src/main/java/powerup/systers/com/ui/scenario_over_screen/ScenarioOverActivity.java

The mapping of dialogues was incorrect because the value of SessionHistory.currQID was updated and overwritten in GameActivity because of trigerring of overridden metods.
A better way to ensure proper value of SessionHistory.currQID would be to update it in ScenarioOverActivity .
Fixes #1264 
- Code

Fixed to populate scenarios with correct dialogues

---

PowerUp/app/src/main/java/powerup/systers/com/data/SessionHistory.java
PowerUp/app/src/main/java/powerup/systers/com/ui/StartActivity.java
PowerUp/app/src/main/java/powerup/systers/com/ui/final_avatar_room/FinalAvatarActivity.java
PowerUp/app/src/main/java/powerup/systers/com/ui/scenario_over_screen/ScenarioOverActivity.java
PowerUp/app/src/main/java/powerup/systers/com/utils/PowerUpUtils.java

In this PR I have fixed the behavior of LOAD button such that it launches Level 2 once level 1 is complete.
A static boolean variable is used in PowerUpUtils.java, level1Complete, that is initially set to false. It sets to true once Level 1 is completed. Now when LOAD GAME button is pressed on Start activity the value of the variable is checked first and Level 1 or Level 2 is launched accordingly.
Fixes #1287 
- Code
Steps to reproduce:
1. Complete Level 1 and go to map for Level 2
2. Press the home button on the Map screen and go the start screen
3.  Press the LOAD Game Button
It now launches Map screen of Level 2

Rectified behaviour of LOAD Game

---

PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity/GameActivity.java
PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity/GameScreenContract.java
PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity/GameScreenPresenter.java
PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity_level2/GameLevel2Activity.java
PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity_level2/GameScreenLevel2Contract.java
PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity_level2/GameScreenLevel2Presenter.java
PowerUp/app/src/main/res/drawable-xxxhdpi/btn_bg.xml
PowerUp/app/src/main/res/drawable-xxxhdpi/btn_bg_red.xml

Fixed the error where the last answer was needed to be clicked twice to end a scenario
Fixes #1277 
- Code
- Bug fix (non-breaking change which fixes an issue
The changes can be reproduced by playing through any scenario.
The scenario ends after pressing the last answer only once.

Rectified the double click issue

---

PowerUp/app/src/main/java/powerup/systers/com/save_the_blood_game/SaveTheBloodEndActivity.java
PowerUp/app/src/main/java/powerup/systers/com/ui/game_activity_level2/GameLevel2Activity.java
PowerUp/app/src/main/java/powerup/systers/com/ui/scenario_over_screen_level2/ScenarioOverLevel2Activity.java
PowerUp/app/src/main/java/powerup/systers/com/utils/PowerUpUtils.java

The error was in SaveTheBloodEndActivity where the variable OpenedStatus was not reset to false
While fixing this issue, I came across another problem. 
Once all the scenes in Level 2 are played, no matter which scene is chosen for replay, the home scenario was launched always. The problem was in switch case block inside the click listener for replay button. I fixed this as well
Fixes #1295 
- Code
Steps to reproduce:
1. Complete the save the blood game
2. Launch map again from the game over screen
3. Choose any scenario to replay
The selected scenario will be replayed whereas initially Save Blood game was always launched.

Fixed the ending case for  save blood
